version: '3'
services:
  app:
    container_name: analog_api
    image: quentinchampenois/analog_api:latest
    env_file: .env
    restart: always
    volumes:
      - api:/usr/src/app/
    depends_on:
      - postgres
    networks:
      - default
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

volumes:
  api:
  postgres:
